export const CATEGORY_META: Record<string, {
  icon: string
  color: string
  bg: string
  labelEn: string
  labelBn: string
}> = {
  food: { icon: '🍽️', color: '#f59e0b', bg: '#f59e0b15', labelEn: 'Food', labelBn: 'খাবার' },
  transport: { icon: '🚗', color: '#3b82f6', bg: '#3b82f615', labelEn: 'Transport', labelBn: 'যাতায়াত' },
  utilities: { icon: '💡', color: '#eab308', bg: '#eab30815', labelEn: 'Utilities', labelBn: 'বিল' },
  health: { icon: '💊', color: '#ef4444', bg: '#ef444415', labelEn: 'Health', labelBn: 'স্বাস্থ্য' },
  education: { icon: '📚', color: '#8b5cf6', bg: '#8b5cf615', labelEn: 'Education', labelBn: 'শিক্ষা' },
  entertainment: { icon: '🎬', color: '#ec4899', bg: '#ec489915', labelEn: 'Entertainment', labelBn: 'বিনোদন' },
  shopping: { icon: '🛍️', color: '#f97316', bg: '#f9731615', labelEn: 'Shopping', labelBn: 'কেনাকাটা' },
  rent: { icon: '🏠', color: '#06b6d4', bg: '#06b6d415', labelEn: 'Rent', labelBn: 'ভাড়া' },
  other: { icon: '📦', color: '#6b7280', bg: '#6b728015', labelEn: 'Other', labelBn: 'অন্যান্য' },
  transfer: { icon: '🔄', color: '#6366f1', bg: '#6366f115', labelEn: 'Transfer', labelBn: 'স্থানান্তর' },
  adjustment: { icon: '⚖️', color: '#f59e0b', bg: '#f59e0b15', labelEn: 'Adjustment', labelBn: 'সমন্বয়' },
  salary: { icon: '💰', color: '#22c55e', bg: '#22c55e15', labelEn: 'Salary', labelBn: 'বেতন' },
  freelance: { icon: '💻', color: '#6366f1', bg: '#6366f115', labelEn: 'Freelance', labelBn: 'ফ্রিল্যান্স' },
  investment: { icon: '📈', color: '#10b981', bg: '#10b98115', labelEn: 'Investment', labelBn: 'বিনিয়োগ' },
  gift: { icon: '🎁', color: '#ec4899', bg: '#ec489915', labelEn: 'Gift', labelBn: 'উপহার' },
  'other-income': { icon: '📥', color: '#6b7280', bg: '#6b728015', labelEn: 'Other Income', labelBn: 'অন্যান্য আয়' },
  'loan-repayment': { icon: '🔄', color: '#ef4444', bg: '#ef444415', labelEn: 'Loan Repayment', labelBn: 'ঋণ পরিশোধ' },
}

export const EXPENSE_CATEGORIES = [
  'food', 'transport', 'utilities', 'health',
  'education', 'entertainment', 'shopping', 'rent', 'transfer', 'adjustment', 'loan-repayment', 'other',
] as const

export const INCOME_CATEGORIES = [
  'salary', 'freelance', 'investment', 'gift', 'transfer', 'adjustment', 'other-income',
] as const

export const WALLET_TYPES = [
  { type: 'cash', icon: '💵', label: 'Cash' },
  { type: 'bank', icon: '🏦', label: 'Bank' },
  { type: 'mobile', icon: '📱', label: 'Mobile' },
  { type: 'savings', icon: '🏺', label: 'Savings' },
] as const

const en = {
  overview: 'Overview',
  transactions: 'Transactions',
  bills: 'Bills',
  loans: 'Loans',
  analytics: 'Analytics',
  budget: 'Budget',
  goals: 'Goals',
  totalBalance: 'Total Balance',
  thisMonth: 'This Month',
  income: 'Income',
  expense: 'Expense',
  balance: 'Balance',
  categoryBreakdown: 'Category Breakdown',
  emptyTx: 'No transactions yet',
  emptySub: 'Add your first income or expense to get started',
  emptyLoan: 'No active loans',
  emptyLoanSub: 'Track money you lend or borrow',
  given: 'Given',
  taken: 'Taken',
  givenRemaining: 'Given Remaining',
  takenRemaining: 'Taken Remaining',
  activeLoans: 'Active Loans',
  completedLoans: 'Completed Loans',
  dueDate: 'Due',
  principal: 'Principal',
  repaidPercent: 'repaid',
  status: 'Status',
  settled: 'Settled',
  active: 'Active',
  add: 'Add',
  repay: 'Repay',
  currentBalance: 'Current Balance',
  maxRepayHint: 'Max repay',
  financialHealth: 'Financial Health',
  savingsRate: 'Savings Rate',
  weeklyAvg: 'Weekly Average',
  topCategory: 'Top Category',
  financialInsights: 'Financial Insights',
  viewAll: 'View All',
  recentTransactions: 'Recent Transactions',
  seeAll: 'See All',
  addTransaction: 'Add Transaction',
  addLoan: 'Add Loan',
  addGoal: 'Add Goal',
  amount: 'Amount',
  note: 'Note',
  date: 'Date',
  category: 'Category',
  type: 'Type',
  expense_type: 'Expense',
  income_type: 'Income',
  personName: 'Person Name',
  direction: 'Direction',
  targetAmount: 'Target Amount',
  currentAmount: 'Current Amount',
  deadline: 'Deadline',
  title: 'Title',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  history: 'History',
  reactivate: 'Reactivate',
  search: 'Search transactions...',
  filterBy: 'Filter by',
  sortBy: 'Sort by',
  all: 'All',
  wallet: 'Wallet',
  subscriptions: 'Subscriptions',
  upcomingBills: 'Upcoming Bills',
  monthlyBudget: 'Monthly Budget',
  budgetUsed: 'of budget used',
  remaining: 'Remaining',
  overspent: 'Overspent',
  onTrack: 'On Track',
  goalProgress: 'Goal Progress',
  daysLeft: 'days left',
  overdue: 'Overdue',
}

export const TRANSLATIONS = {
  en,
  bn: {
    ...en,
    overview: 'সংক্ষেপ',
    transactions: 'লেনদেন',
    bills: 'বিল',
    loans: 'ঋণ',
    analytics: 'বিশ্লেষণ',
    budget: 'বাজেট',
    goals: 'লক্ষ্য',
    totalBalance: 'মোট ব্যালেন্স',
    income: 'আয়',
    expense: 'ব্যয়',
    balance: 'ব্যালেন্স',
    emptyTx: 'কোনো লেনদেন নেই',
    emptySub: 'শুরু করতে আয় বা ব্যয় যোগ করুন',
    addTransaction: 'লেনদেন যোগ করুন',
    amount: 'পরিমাণ',
    note: 'নোট',
    date: 'তারিখ',
    category: 'বিভাগ',
    expense_type: 'ব্যয়',
    income_type: 'আয়',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    edit: 'সম্পাদনা',
    delete: 'মুছুন',
    search: 'লেনদেন খুঁজুন...',
    all: 'সব',
    wallet: 'ওয়ালেট',
    subscriptions: 'সাবস্ক্রিপশন',
    upcomingBills: 'আসন্ন বিল',
    monthlyBudget: 'মাসিক বাজেট',
    remaining: 'বাকি',
    overspent: 'অতিরিক্ত ব্যয়',
    overdue: 'মেয়াদোত্তীর্ণ',
  },
}
