export const CATEGORY_META: Record<string, {
  icon: string
  color: string
  bg: string
  labelEn: string
  labelBn: string
}> = {
  food: { icon: '🍽️', color: '#f59e0b', bg: '#f59e0b15', labelEn: 'Food', labelBn: 'খাবার' },
  transport: { icon: '🚗', color: '#3b82f6', bg: '#3b82f615', labelEn: 'Transport', labelBn: 'যাতায়াত' },
  utilities: { icon: '💡', color: '#eab308', bg: '#eab30815', labelEn: 'Utilities', labelBn: 'উপযোগিতা' },
  health: { icon: '💊', color: '#ef4444', bg: '#ef444415', labelEn: 'Health', labelBn: 'স্বাস্থ্য' },
  education: { icon: '📚', color: '#8b5cf6', bg: '#8b5cf615', labelEn: 'Education', labelBn: 'শিক্ষা' },
  entertainment: { icon: '🎬', color: '#ec4899', bg: '#ec489915', labelEn: 'Entertainment', labelBn: 'বিনোদন' },
  shopping: { icon: '🛍️', color: '#f97316', bg: '#f9731615', labelEn: 'Shopping', labelBn: 'কেনাকাটা' },
  rent: { icon: '🏠', color: '#06b6d4', bg: '#06b6d415', labelEn: 'Rent', labelBn: 'ভাড়া' },
  other: { icon: '📦', color: '#6b7280', bg: '#6b728015', labelEn: 'Other', labelBn: 'অন্যান্য' },
  salary: { icon: '💰', color: '#22c55e', bg: '#22c55e15', labelEn: 'Salary', labelBn: 'বেতন' },
  freelance: { icon: '💻', color: '#6366f1', bg: '#6366f115', labelEn: 'Freelance', labelBn: 'ফ্রিল্যান্স' },
  investment: { icon: '📈', color: '#10b981', bg: '#10b98115', labelEn: 'Investment', labelBn: 'বিনিয়োগ' },
  gift: { icon: '🎁', color: '#ec4899', bg: '#ec489915', labelEn: 'Gift', labelBn: 'উপহার' },
  'other-income': { icon: '📥', color: '#6b7280', bg: '#6b728015', labelEn: 'Other Income', labelBn: 'অন্যান্য আয়' },
}

export const EXPENSE_CATEGORIES = [
  'food', 'transport', 'utilities', 'health',
  'education', 'entertainment', 'shopping', 'rent', 'other'
] as const

export const INCOME_CATEGORIES = [
  'salary', 'freelance', 'investment', 'gift', 'other-income'
] as const

export const WALLET_TYPES = [
  { type: 'cash', icon: '💵', label: 'Cash' },
  { type: 'bank', icon: '🏦', label: 'Bank' },
  { type: 'mobile', icon: '📱', label: 'Mobile' },
  { type: 'savings', icon: '🏺', label: 'Savings' },
] as const

export const TRANSLATIONS = {
  en: {
    overview: 'Overview',
    transactions: 'Transactions',
    loans: 'Loans',
    analytics: 'Analytics',
    budget: 'Budget',
    goals: 'Goals',
    totalBalance: 'Total Balance',
    thisMonth: 'This Month',
    income: 'Income',
    expense: 'Expense',
    balance: 'Balance',
    categoryBreakdown: 'Category Breakdown',
    emptyTx: 'No transactions yet',
    emptySub: 'Add your first transaction to get started',
    emptyLoan: 'No active loans',
    emptyLoanSub: 'Track money you lend or borrow',
    given: 'Given',
    taken: 'Taken',
    givenRemaining: 'Given Remaining',
    takenRemaining: 'Taken Remaining',
    activeLoans: 'Active Loans',
    completedLoans: 'Completed Loans',
    dueDate: 'Due',
    principal: 'Principal',
    repaidPercent: 'repaid',
    status: 'Status',
    settled: 'Settled',
    active: 'Active',
    add: 'Add',
    repay: 'Repay',
    currentBalance: 'Current Balance',
    maxRepayHint: 'Max repay',
    financialHealth: 'Financial Health',
    savingsRate: 'Savings Rate',
    weeklyAvg: 'Weekly Average',
    topCategory: 'Top Category',
    financialInsights: 'Financial Insights',
    viewAll: 'View All',
    recentTransactions: 'Recent Transactions',
    seeAll: 'See All',
    addTransaction: 'Add Transaction',
    addLoan: 'Add Loan',
    addGoal: 'Add Goal',
    amount: 'Amount',
    note: 'Note',
    date: 'Date',
    category: 'Category',
    type: 'Type',
    expense_type: 'Expense',
    income_type: 'Income',
    personName: 'Person Name',
    direction: 'Direction',
    targetAmount: 'Target Amount',
    currentAmount: 'Current Amount',
    deadline: 'Deadline',
    title: 'Title',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    history: 'History',
    reactivate: 'Reactivate',
    search: 'Search transactions...',
    filterBy: 'Filter by',
    sortBy: 'Sort by',
    all: 'All',
    wallet: 'Wallet',
    subscriptions: 'Subscriptions',
    upcomingBills: 'Upcoming Bills',
    monthlyBudget: 'Monthly Budget',
    budgetUsed: 'of budget used',
    remaining: 'Remaining',
    overspent: 'Overspent',
    onTrack: 'On Track',
    goalProgress: 'Goal Progress',
    daysLeft: 'days left',
    overdue: 'Overdue',
  },
  bn: {
    overview: 'সংক্ষেপ',
    transactions: 'লেনদেন',
    loans: 'ঋণ',
    analytics: 'বিশ্লেষণ',
    budget: 'বাজেট',
    goals: 'লক্ষ্য',
    totalBalance: 'মোট ব্যালেন্স',
    thisMonth: 'এই মাস',
    income: 'আয়',
    expense: 'ব্যয়',
    balance: 'ব্যালেন্স',
    categoryBreakdown: 'বিভাগ অনুযায়ী',
    emptyTx: 'কোনো লেনদেন নেই',
    emptySub: 'শুরু করতে আপনার প্রথম লেনদেন যোগ করুন',
    emptyLoan: 'কোনো সক্রিয় ঋণ নেই',
    emptyLoanSub: 'আপনি যে টাকা ধার দেন বা নেন তা ট্র্যাক করুন',
    given: 'দেওয়া',
    taken: 'নেওয়া',
    givenRemaining: 'দেওয়া বাকি',
    takenRemaining: 'নেওয়া বাকি',
    activeLoans: 'সক্রিয় ঋণ',
    completedLoans: 'সম্পন্ন ঋণ',
    dueDate: 'নির্ধারিত তারিখ',
    principal: 'মূলধন',
    repaidPercent: 'পরিশোধিত',
    status: 'অবস্থা',
    settled: 'নিষ্পত্তি',
    active: 'সক্রিয়',
    add: 'যোগ',
    repay: 'পরিশোধ',
    currentBalance: 'বর্তমান ব্যালেন্স',
    maxRepayHint: 'সর্বোচ্চ পরিশোধ',
    financialHealth: 'আর্থিক স্বাস্থ্য',
    savingsRate: 'সঞ্চয়ের হার',
    weeklyAvg: 'সাপ্তাহিক গড়',
    topCategory: 'শীর্ষ বিভাগ',
    financialInsights: 'আর্থিক অন্তর্দৃষ্টি',
    viewAll: 'সব দেখুন',
    recentTransactions: 'সাম্প্রতিক লেনদেন',
    seeAll: 'সব দেখুন',
    addTransaction: 'লেনদেন যোগ করুন',
    addLoan: 'ঋণ যোগ করুন',
    addGoal: 'লক্ষ্য যোগ করুন',
    amount: 'পরিমাণ',
    note: 'নোট',
    date: 'তারিখ',
    category: 'বিভাগ',
    type: 'ধরন',
    expense_type: 'ব্যয়',
    income_type: 'আয়',
    personName: 'ব্যক্তির নাম',
    direction: 'দিক',
    targetAmount: 'লক্ষ্যমাত্রা',
    currentAmount: 'বর্তমান পরিমাণ',
    deadline: 'শেষ তারিখ',
    title: 'শিরোনাম',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    history: 'ইতিহাস',
    reactivate: 'পুনরায় সক্রিয়',
    search: 'লেনদেন খুঁজুন...',
    filterBy: 'ফিল্টার',
    sortBy: 'সাজান',
    all: 'সব',
    wallet: 'ওয়ালেট',
    subscriptions: 'সাবস্ক্রিপশন',
    upcomingBills: 'আসন্ন বিল',
    monthlyBudget: 'মাসিক বাজেট',
    budgetUsed: 'বাজেট ব্যবহৃত',
    remaining: 'বাকি',
    overspent: 'অতিরিক্ত ব্যয়',
    onTrack: 'ঠিক আছে',
    goalProgress: 'লক্ষ্যের অগ্রগতি',
    daysLeft: 'দিন বাকি',
    overdue: 'মেয়াদোত্তীর্ণ',
  },
}
